version: '2'
services:
  web_service:
    build: .
    image: emilfrontend
    container_name: emilfrontend

    ports:
      - 9000:9000
      - 3000:3000

    env_file:
      - ./.env

    volumes:
      - .:/src

    networks:
      - baseapi_default

networks:
  baseapi_default:
    driver: bridge